# Handling exception errors: try-except
#
# new_list=[2,4,6,'california']
#
#
# #try except
# for element in new_list:
#     try:
#         print(element/2)
#     except:
#         print("The element is not a number")

# while-break
n=4
while n >0:
    print(n)
    n=n-1
    if n==2:
        break
print('loop ended')